var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/blog/route.js")
R.c("server/chunks/node_modules_next_f776cd42._.js")
R.c("server/chunks/node_modules_@auth_core_36df0127._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_868b124b._.js")
R.c("server/chunks/node_modules_zod_v4_dead09ad._.js")
R.c("server/chunks/node_modules_518fb317._.js")
R.c("server/chunks/[root-of-the-server]__81471de7._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_blog_route_actions_554ae564.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/blog/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/blog/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
