// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[...slug]" | "/about" | "/admin" | "/admin/blog" | "/admin/blog/new" | "/admin/case-studies" | "/admin/case-studies/new" | "/admin/clients" | "/admin/clients/new" | "/admin/homepage" | "/admin/messages" | "/admin/pages" | "/admin/pages/[id]" | "/admin/profile" | "/admin/redirects" | "/admin/seo-results" | "/admin/seo-score" | "/admin/settings" | "/admin/settings/branding" | "/admin/settings/general" | "/admin/tools" | "/admin/tools/new" | "/admin/users" | "/blog" | "/blog/[slug]" | "/contact" | "/gizlilik-politikasi" | "/hakkimizda" | "/hizmetler" | "/hizmetler/google-ads-yonetimi" | "/hizmetler/icerik-pazarlamasi" | "/hizmetler/meta-ads" | "/hizmetler/raporlama-analiz" | "/hizmetler/seo-optimizasyonu" | "/hizmetler/sosyal-medya-yonetimi" | "/iletisim" | "/kariyer" | "/kullanim-kosullari" | "/kvkk-aydinlatma-metni" | "/login" | "/referanslar" | "/referanslar/[slug]" | "/seo-analysis" | "/services"
type AppRouteHandlerRoutes = "/api/admin/404-logs" | "/api/admin/blog" | "/api/admin/case-studies" | "/api/admin/clients" | "/api/admin/homepage-hero" | "/api/admin/pages" | "/api/admin/pages/[id]" | "/api/admin/profile" | "/api/admin/redirects" | "/api/admin/redirects/[id]" | "/api/admin/settings/branding" | "/api/admin/settings/general" | "/api/auth/[...nextauth]" | "/api/blog" | "/api/contact" | "/api/log-404" | "/api/seed" | "/api/seo/analyze" | "/api/seo/detailed-report"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[...slug]": { "slug": string[]; }
  "/about": {}
  "/admin": {}
  "/admin/blog": {}
  "/admin/blog/new": {}
  "/admin/case-studies": {}
  "/admin/case-studies/new": {}
  "/admin/clients": {}
  "/admin/clients/new": {}
  "/admin/homepage": {}
  "/admin/messages": {}
  "/admin/pages": {}
  "/admin/pages/[id]": { "id": string; }
  "/admin/profile": {}
  "/admin/redirects": {}
  "/admin/seo-results": {}
  "/admin/seo-score": {}
  "/admin/settings": {}
  "/admin/settings/branding": {}
  "/admin/settings/general": {}
  "/admin/tools": {}
  "/admin/tools/new": {}
  "/admin/users": {}
  "/api/admin/404-logs": {}
  "/api/admin/blog": {}
  "/api/admin/case-studies": {}
  "/api/admin/clients": {}
  "/api/admin/homepage-hero": {}
  "/api/admin/pages": {}
  "/api/admin/pages/[id]": { "id": string; }
  "/api/admin/profile": {}
  "/api/admin/redirects": {}
  "/api/admin/redirects/[id]": { "id": string; }
  "/api/admin/settings/branding": {}
  "/api/admin/settings/general": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/blog": {}
  "/api/contact": {}
  "/api/log-404": {}
  "/api/seed": {}
  "/api/seo/analyze": {}
  "/api/seo/detailed-report": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/contact": {}
  "/gizlilik-politikasi": {}
  "/hakkimizda": {}
  "/hizmetler": {}
  "/hizmetler/google-ads-yonetimi": {}
  "/hizmetler/icerik-pazarlamasi": {}
  "/hizmetler/meta-ads": {}
  "/hizmetler/raporlama-analiz": {}
  "/hizmetler/seo-optimizasyonu": {}
  "/hizmetler/sosyal-medya-yonetimi": {}
  "/iletisim": {}
  "/kariyer": {}
  "/kullanim-kosullari": {}
  "/kvkk-aydinlatma-metni": {}
  "/login": {}
  "/referanslar": {}
  "/referanslar/[slug]": { "slug": string; }
  "/seo-analysis": {}
  "/services": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
