var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a36c45d7._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_5fb16825.js")
R.c("server/chunks/ssr/[root-of-the-server]__2f2638b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_d03d2993.js")
R.c("server/chunks/ssr/[root-of-the-server]__7962e846._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4a0abb1d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6cee8012._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3fd9f0f8._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_0f6131ce._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(32397)
module.exports=R.m(32397).exports
