// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/case-studies/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/case-studies/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/case-studies/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/case-studies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/clients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/clients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients">> = Specific
  const handler = {} as typeof import("../../src/app/admin/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/homepage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/homepage">> = Specific
  const handler = {} as typeof import("../../src/app/admin/homepage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/redirects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/redirects">> = Specific
  const handler = {} as typeof import("../../src/app/admin/redirects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/seo-results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/seo-results">> = Specific
  const handler = {} as typeof import("../../src/app/admin/seo-results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/seo-score/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/seo-score">> = Specific
  const handler = {} as typeof import("../../src/app/admin/seo-score/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/branding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/branding">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/branding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/general">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tools/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tools/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tools/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tools">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gizlilik-politikasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gizlilik-politikasi">> = Specific
  const handler = {} as typeof import("../../src/app/gizlilik-politikasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hakkimizda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hakkimizda">> = Specific
  const handler = {} as typeof import("../../src/app/hakkimizda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hizmetler/google-ads-yonetimi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hizmetler/google-ads-yonetimi">> = Specific
  const handler = {} as typeof import("../../src/app/hizmetler/google-ads-yonetimi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hizmetler/icerik-pazarlamasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hizmetler/icerik-pazarlamasi">> = Specific
  const handler = {} as typeof import("../../src/app/hizmetler/icerik-pazarlamasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hizmetler/meta-ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hizmetler/meta-ads">> = Specific
  const handler = {} as typeof import("../../src/app/hizmetler/meta-ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hizmetler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hizmetler">> = Specific
  const handler = {} as typeof import("../../src/app/hizmetler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hizmetler/raporlama-analiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hizmetler/raporlama-analiz">> = Specific
  const handler = {} as typeof import("../../src/app/hizmetler/raporlama-analiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hizmetler/seo-optimizasyonu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hizmetler/seo-optimizasyonu">> = Specific
  const handler = {} as typeof import("../../src/app/hizmetler/seo-optimizasyonu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hizmetler/sosyal-medya-yonetimi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hizmetler/sosyal-medya-yonetimi">> = Specific
  const handler = {} as typeof import("../../src/app/hizmetler/sosyal-medya-yonetimi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/iletisim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/iletisim">> = Specific
  const handler = {} as typeof import("../../src/app/iletisim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kariyer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kariyer">> = Specific
  const handler = {} as typeof import("../../src/app/kariyer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kullanim-kosullari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kullanim-kosullari">> = Specific
  const handler = {} as typeof import("../../src/app/kullanim-kosullari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kvkk-aydinlatma-metni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kvkk-aydinlatma-metni">> = Specific
  const handler = {} as typeof import("../../src/app/kvkk-aydinlatma-metni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/referanslar/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referanslar/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/referanslar/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/referanslar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referanslar">> = Specific
  const handler = {} as typeof import("../../src/app/referanslar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/seo-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seo-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/seo-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/404-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/404-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/404-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/case-studies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/case-studies">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/case-studies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/clients">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/homepage-hero/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/homepage-hero">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/homepage-hero/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pages">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/redirects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/redirects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/redirects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/redirects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/redirects">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/redirects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/branding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings/branding">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/branding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/general/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings/general">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/general/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/log-404/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/log-404">> = Specific
  const handler = {} as typeof import("../../src/app/api/log-404/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed">> = Specific
  const handler = {} as typeof import("../../src/app/api/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seo/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seo/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/seo/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seo/detailed-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seo/detailed-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/seo/detailed-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
